version: '3.7'
services:
  db:
    image: mysql:5.7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=task-logger
      - MYSQL_USER=task-user
      - MYSQL_PASSWORD=123456789
    ports:
      - '3306:3306'
    networks:
      - backend

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - 8081:8081
      - 9229:9229
    expose:
      - "8081"
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    ports:
      - 80:3000
    expose:
      - "80"
    stdin_open: true
    networks:
      - backend


networks:
  backend:
