version: '3.7'
services:
  db:
    image: mysql:5.7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=task-logger
      - MYSQL_USER=task-user
      - MYSQL_PASSWORD=123456789
    ports:
      - '3306:3306'
    networks:
      - backend

  backend:
    image: registry.code.fbi.h-da.de/istlehieu/fwe-ws20-21-753953-ha1
    ports:
      - 8081:8081
      - 9229:9229
    expose:
      - "8081"
    networks:
      - backend


networks:
  backend:
